name: prano-app

services:
  mongo:
    image: mongo:7.0.12
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - prano-app
    restart: unless-stopped

  api:
    build:
      context: ./server
      target: production
    networks:
      - prano-app
    depends_on:
      - mongo
    restart: unless-stopped

  web:
    build:
      context: ./site
      target: production
    networks:
      - prano-app
    depends_on:
      - api
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./scripts:/scripts
    networks:
      - prano-app
    depends_on:
      - web
    restart: unless-stopped
# Тимчасово закоментив, щоб сертбот не намагався поновити сертифікати
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
#    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERT_EMAIL} -d ${DOMAIN} --agree-tos
#    networks:
#      - prano-app
#    depends_on:
#      - nginx

volumes: # /var/lib/docker
  mongo_data:
networks:
  prano-app:
    driver: bridge
