version: "3.9"

services:
  web:
    build:
      context: ./site
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./site:/app
      - /app/node_modules
    restart: on-failure
