const EEmailActions = {
    WELCOME: "WELCOME",
    FORGOT_PASSWORD: "FORGOT_PASSWORD",
    PASSWORD_CHANGED: "PASSWORD_CHANGED",
    ORDER_CREATED_MANAGER: "ORDER_CREATED_MANAGER",
    ORDER_CREATED_USER: "ORDER_CREATED_USER",
}

module.exports = {
    EEmailActions
}