module.exports = {
    advertisementService: require("./advertisement.service"),
    authService: require("./auth.service"),
    axiosService: require("./axios.service"),
    categoryService: require("./category.service"),
    ccService: require("./cc.service"),
    emailService: require("./email.service"),
    merchandiseService: require("./merchandise.service"),
    orderService: require("./order.service"),
    passwordService: require("./password.service"),
    postService: require("./post.service"),
    productService: require("./product.service"),
    telegramService: require("./telegram.service"),
    tokenService: require("./token.service"),
    userService: require("./user.service"),
}